version: '3'
services:
  web:
    ports:
      - "80:80"
    image: stoffel/web:7.4
    container_name: cmsqlite_web
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
    volumes:
      - .:/var/www/html
      - ./docker/sites-available:/etc/apache2/sites-available
