version: '3'
services:
  web:
    build: ./docker
    ports:
      - "80:80"
    image: cmsqlite/web
    container_name: cmsqlite_web
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
    volumes:
      - .:/var/www/html
